export default function createSkillsToCharacter(heroClass, typeOfSkills) {
  let { data } = {};
  switch (typeOfSkills) {
    case 0:
      switch (heroClass) {
        case "Mage":
          data = {
            firstSkill: {
              nameOfSkill: "Kula ognia",
              descriptionOfSkill: "Przywołanie kuli ognia, zadająca duże obrażenia. Po trafieniu przeciwnika zadaje dodatkowe obrażenia od ognia przez określony czas.",
              pointsOfMana: 25,
              valueOfSkill: 0.5,
              durationTime: 0,
              castTime: 2000,
              recastTime: 5000,
              numberOfSkill: 1,
              countOfDots: 2,
              typeOfSkill: 0,
              targetOfSkill: "attack",
              dotValue: 0.1,
            },
            secondSkill: {
              nameOfSkill: "Błyskawica",
              descriptionOfSkill: "Zsyła błyskawice na pole walki zadając ogromne obrażenia.",
              pointsOfMana: 70,
              valueOfSkill: 0.6,
              durationTime: 0,
              castTime: 5000,
              recastTime: 10000,
              numberOfSkill: 2,
              countOfDots: 0,
              typeOfSkill: 0,
              targetOfSkill: "damage",
              dotValue: 0,
            },
            thirdSkill: {
              nameOfSkill: "Przypływ many",
              descriptionOfSkill: "Przywraca punkty many.",
              pointsOfMana: 70,
              valueOfSkill: 0.3,
              durationTime: 0,
              castTime: 5000,
              recastTime: 10000,
              numberOfSkill: 3,
              countOfDots: 0,
              typeOfSkill: 2,
              targetOfSkill: "restoreManaPoints",
              dotValue: 0,
            },
            forthSkill: {
              nameOfSkill: "Medytacja",
              descriptionOfSkill: "Zwiększa poziom punktów many o 20%.",
              pointsOfMana: 50,
              valueOfSkill: 0.2,
              durationTime: 10000,
              castTime: 2000,
              recastTime: 20000,
              numberOfSkill: 4,
              countOfDots: 0,
              typeOfSkill: 1,
              targetOfSkill: "manaPoints",
              dotValue: 0,
            },
            fifthSkill: {
              nameOfSkill: "Pyromaniak",
              descriptionOfSkill: "Zwiększa szanse na krytyczne obrażenia o 20%.",
              pointsOfMana: 70,
              valueOfSkill: 0.3,
              durationTime: 10000,
              castTime: 5000,
              recastTime: 20000,
              numberOfSkill: 5,
              countOfDots: 0,
              typeOfSkill: 1,
              targetOfSkill: "crit",
              dotValue: 0,
            },
            sixthSkill: {
              nameOfSkill: "Ognisty Meteoryt",
              descriptionOfSkill:
                "Przywołanie ogromnego ognistego meteorytu zadający ogromne obrażenia. Na obszarze uderzenia pozostaje ogień, który zadaje dodatkowe obrażenia od ognia przeciwnikom przez pewnien czas.",
              pointsOfMana: 200,
              valueOfSkill: 0.7,
              durationTime: 0,
              castTime: 2000,
              recastTime: 10000,
              numberOfSkill: 6,
              countOfDots: 3,
              typeOfSkill: 0,
              targetOfSkill: "damage",
              dotValue: 0.2,
            },
          };
          break;
        case "Warrior":
          data = {
            firstSkill: {
              nameOfSkill: "Błyskawiczne pchnięcie",
              descriptionOfSkill: "Szybki atak przebijający przez lukę w obronie przeciwnika zadający duze obrażenia.",
              pointsOfMana: 25,
              valueOfSkill: 0.5,
              durationTime: 0,
              castTime: 2000,
              recastTime: 10000,
              numberOfSkill: 1,
              countOfDots: 0,
              typeOfSkill: 0,
              targetOfSkill: "attack",
              dotValue: 0,
            },
            secondSkill: {
              nameOfSkill: "Oślepiająca zbroja",
              descriptionOfSkill: "Zwiększa szansę na unik o 10%.",
              pointsOfMana: 30,
              valueOfSkill: 0.1,
              durationTime: 10000,
              castTime: 2000,
              recastTime: 20000,
              numberOfSkill: 2,
              countOfDots: 0,
              typeOfSkill: 1,
              targetOfSkill: "dodge",
              dotValue: 0,
            },
            thirdSkill: {
              nameOfSkill: "Silna wola",
              descriptionOfSkill: "Przywraca punkty życia.",
              pointsOfMana: 70,
              valueOfSkill: 0.2,
              durationTime: 0,
              castTime: 2000,
              recastTime: 10000,
              numberOfSkill: 3,
              countOfDots: 0,
              typeOfSkill: 2,
              targetOfSkill: "restoreHealthPoints",
              dotValue: 0,
            },
            forthSkill: {
              nameOfSkill: "Podręczna tarcza",
              descriptionOfSkill: "Zwiększa obronę o 20%.",
              pointsOfMana: 50,
              valueOfSkill: 0.2,
              durationTime: 10000,
              castTime: 2000,
              recastTime: 20000,
              numberOfSkill: 4,
              countOfDots: 0,
              typeOfSkill: 1,
              targetOfSkill: "defense",
              dotValue: 0,
            },
            fifthSkill: {
              nameOfSkill: "Heroiczna Klinga",
              descriptionOfSkill: "Zadaje duże obrażenia poprzez wykorzystanie legendarnego miecza.",
              pointsOfMana: 70,
              valueOfSkill: 0.6,
              durationTime: 0,
              castTime: 5000,
              recastTime: 10000,
              numberOfSkill: 5,
              countOfDots: 0,
              typeOfSkill: 0,
              targetOfSkill: "attack",
              dotValue: 0,
            },
            sixthSkill: {
              nameOfSkill: "Zimna Krew",
              descriptionOfSkill: "Zwiększa poziom punktów życia o 20%.",
              pointsOfMana: 50,
              valueOfSkill: 0.2,
              durationTime: 10000,
              castTime: 2000,
              recastTime: 20000,
              numberOfSkill: 6,
              countOfDots: 0,
              typeOfSkill: 1,
              targetOfSkill: "healthPoints",
              dotValue: 0,
            },
          };
          break;
        case "Hunter":
          data = {
            firstSkill: {
              nameOfSkill: "Złota strzała",
              descriptionOfSkill: "Powoduje wystrzelenie złotej strzały, która zadaje ogromne obrażenia.",
              pointsOfMana: 25,
              valueOfSkill: 0.3,
              durationTime: 0,
              castTime: 2000,
              recastTime: 10000,
              numberOfSkill: 1,
              countOfDots: 0,
              typeOfSkill: 0,
              targetOfSkill: "attack",
              dotValue: 0,
            },
            secondSkill: {
              nameOfSkill: "Zatruta strzała",
              descriptionOfSkill: "Powoduje wystrzelenie zatrutej strzały, która zadaje dodatkowe obrażenia przez określony czas od zatrucia.",
              pointsOfMana: 70,
              valueOfSkill: 0.5,
              durationTime: 0,
              castTime: 5000,
              recastTime: 11000,
              numberOfSkill: 2,
              countOfDots: 2,
              typeOfSkill: 0,
              targetOfSkill: "damage",
              dotValue: 0.2,
            },
            thirdSkill: {
              nameOfSkill: "Ukrycie w cieniu",
              descriptionOfSkill: "Zwiększenie szansy na unik o 10%.",
              pointsOfMana: 70,
              valueOfSkill: 0.1,
              durationTime: 10000,
              castTime: 2000,
              recastTime: 20000,
              numberOfSkill: 3,
              countOfDots: 0,
              typeOfSkill: 1,
              targetOfSkill: "dodge",
              dotValue: 0,
            },
            forthSkill: {
              nameOfSkill: "Czarna strzała",
              descriptionOfSkill: "Wystrzelenie czarnej grozy, która zadaje ogromne obrażenia poprzez przebicie pancerza. Trudna do zobaczenia.",
              pointsOfMana: 50,
              valueOfSkill: 0.6,
              durationTime: 0,
              castTime: 2000,
              recastTime: 10000,
              numberOfSkill: 4,
              countOfDots: 2,
              typeOfSkill: 0,
              targetOfSkill: "damage",
              dotValue: 0,
            },
            fifthSkill: {
              nameOfSkill: "Liściasty bandaż",
              descriptionOfSkill: "Przywraca punkty życia.",
              pointsOfMana: 70,
              valueOfSkill: 0.2,
              durationTime: 0,
              castTime: 5000,
              recastTime: 10000,
              numberOfSkill: 5,
              countOfDots: 0,
              typeOfSkill: 2,
              targetOfSkill: "restoreHealthPoints",
              dotValue: 0,
            },
            sixthSkill: {
              nameOfSkill: "Podpalająca strzała",
              descriptionOfSkill: "Wystrzelenie strzały pokrytej ogniem zadaje obrażenia oraz dodatkowe obrażenia od podpalenia przez dany okres czasu.",
              pointsOfMana: 50,
              valueOfSkill: 0.7,
              durationTime: 0,
              castTime: 2000,
              recastTime: 10000,
              numberOfSkill: 6,
              countOfDots: 3,
              typeOfSkill: 0,
              targetOfSkill: "damage",
              dotValue: 0.1,
            },
          };
          break;
        case "Priest":
          data = {
            firstSkill: {
              nameOfSkill: "Światło osądu",
              descriptionOfSkill: "Przywołuje mocne światło, zadające duże obrażenia.",
              pointsOfMana: 25,
              valueOfSkill: 0.45,
              durationTime: 0,
              castTime: 2000,
              recastTime: 10000,
              numberOfSkill: 1,
              countOfDots: 0,
              typeOfSkill: 0,
              targetOfSkill: "attack",
              dotValue: 0,
            },
            secondSkill: {
              nameOfSkill: "Boski Dotyk",
              descriptionOfSkill: "Przywraca punkty życia.",
              pointsOfMana: 70,
              valueOfSkill: 0.5,
              durationTime: 0,
              castTime: 5000,
              recastTime: 15000,
              numberOfSkill: 2,
              countOfDots: 0,
              typeOfSkill: 2,
              targetOfSkill: "restoreHealthPoints",
              dotValue: 0,
            },
            thirdSkill: {
              nameOfSkill: "Przypływ many",
              descriptionOfSkill: "Zwiększa ilość punktów many o 20%",
              pointsOfMana: 70,
              valueOfSkill: 0.2,
              durationTime: 10000,
              castTime: 2000,
              recastTime: 20000,
              numberOfSkill: 3,
              countOfDots: 0,
              typeOfSkill: 1,
              targetOfSkill: "manaPoints",
              dotValue: 0,
            },
            forthSkill: {
              nameOfSkill: "Niebiańska Opatrzność",
              descriptionOfSkill: "Zwiększa obrażenia o 25%.",
              pointsOfMana: 50,
              valueOfSkill: 0.25,
              durationTime: 10000,
              castTime: 2000,
              recastTime: 20000,
              numberOfSkill: 4,
              countOfDots: 0,
              typeOfSkill: 1,
              targetOfSkill: "attack",
              dotValue: 0,
            },
            fifthSkill: {
              nameOfSkill: "Klątwa niewiernego",
              descriptionOfSkill: "Zadaje obrażenia od klątwy. Po użyciu umiejętności przeciwnik pozostaje przeklęty na określony czas w wyniku otrzymuje dodatkowe obrażenia.",
              pointsOfMana: 70,
              valueOfSkill: 0.6,
              durationTime: 0,
              castTime: 5000,
              recastTime: 10000,
              numberOfSkill: 5,
              countOfDots: 3,
              typeOfSkill: 0,
              targetOfSkill: "attack",
              dotValue: 0.15,
            },
            sixthSkill: {
              nameOfSkill: "Ulepszony Boski Dotyk",
              descriptionOfSkill: "Przywraca punkty życia oraz po wykorzystaniu umiejętności,przywraca dodatkowe punkty życia przez określony czas.",
              pointsOfMana: 120,
              valueOfSkill: 0.6,
              durationTime: 0,
              castTime: 3000,
              recastTime: 10000,
              numberOfSkill: 6,
              countOfDots: 3,
              typeOfSkill: 2,
              targetOfSkill: "restoreHealthPoints",
              dotValue: 0.2,
            },
          };
          break;
        case "Berserk":
          data = {
            firstSkill: {
              nameOfSkill: "Cios grozy",
              descriptionOfSkill: "Mocny cios grozy zadaje dodatkowe obrażenia z powodu przerażenia przeciwnika.",
              pointsOfMana: 10,
              valueOfSkill: 0.3,
              durationTime: 0,
              castTime: 2000,
              recastTime: 10000,
              numberOfSkill: 1,
              countOfDots: 0,
              typeOfSkill: 0,
              targetOfSkill: "damage",
              dotValue: 0,
            },
            secondSkill: {
              nameOfSkill: "Podwójne cięcie",
              descriptionOfSkill: "Wyprowadzenie szybkich dwóch mocnych cięc, które zadają taką samą ilość obrażen.",
              pointsOfMana: 25,
              valueOfSkill: 0.6,
              durationTime: 0,
              castTime: 5000,
              recastTime: 10000,
              numberOfSkill: 2,
              countOfDots: 1,
              typeOfSkill: 0,
              targetOfSkill: "damage",
              dotValue: 1,
            },
            thirdSkill: {
              nameOfSkill: "Wzrok Odyna",
              descriptionOfSkill: "Zwiększenie szansy na cios krytyczny o 15%.",
              pointsOfMana: 70,
              valueOfSkill: 0.15,
              durationTime: 10000,
              castTime: 2000,
              recastTime: 20000,
              numberOfSkill: 3,
              countOfDots: 0,
              typeOfSkill: 1,
              targetOfSkill: "crit",
              dotValue: 0,
            },
            forthSkill: {
              nameOfSkill: "Zwycięski róg",
              descriptionOfSkill: "Przywraca określoną ilość punktów życia.",
              pointsOfMana: 50,
              valueOfSkill: 0.3,
              durationTime: 0,
              castTime: 5000,
              recastTime: 10000,
              numberOfSkill: 4,
              countOfDots: 0,
              typeOfSkill: 2,
              targetOfSkill: "restoreHealthPoints",
              dotValue: 0,
            },
            fifthSkill: {
              nameOfSkill: "Krwawe cięcie",
              descriptionOfSkill: "Wyprowadzenie groźnego ataku przebijający pancerz zostawiający głeboką ranę. Dodatkowe obrażenia od krwawienia przez określony czas.",
              pointsOfMana: 70,
              valueOfSkill: 0.5,
              durationTime: 0,
              castTime: 5000,
              recastTime: 10000,
              numberOfSkill: 5,
              countOfDots: 3,
              typeOfSkill: 0,
              targetOfSkill: "damage",
              dotValue: 0.3,
            },
            sixthSkill: {
              nameOfSkill: "Wściekłóść wikinga",
              descriptionOfSkill: "Wszystkie wyprowadzone obrażenia są zwiększone o 25%.",
              pointsOfMana: 100,
              valueOfSkill: 0.25,
              durationTime: 10000,
              castTime: 2000,
              recastTime: 20000,
              numberOfSkill: 6,
              countOfDots: 0,
              typeOfSkill: 1,
              targetOfSkill: "attack",
              dotValue: 0,
            },
          };
          break;
      }
      break;
    case 1:
      switch (heroClass) {
        case "Mage":
          data = {
            firstSkill: {
              nameOfSkill: "Bonus inteligencji",
              descriptionOfSkill: "Zwiększenie podstawowych punktów inteligencji o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 1,
            },
            secondSkill: {
              nameOfSkill: "Bonus wytrzymałości",
              descriptionOfSkill: "Zwiększenie podstawowych punktów wytrzymałości o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 2,
            },
            thirdSkill: {
              nameOfSkill: "Bonus szczęścia",
              descriptionOfSkill: "Zwiększenie podstawowych punktów szczęścia o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 3,
            },
            forthSkill: {
              nameOfSkill: "Bonus zwinności",
              descriptionOfSkill: "Zwiększenie podstawowych punktów zręczności o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 4,
            },
            fifthSkill: {
              nameOfSkill: "Bonus siły",
              descriptionOfSkill: "Zwiększenie podstawowych punktów siły o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 5,
            },
            sixthSkill: {
              nameOfSkill: "Podstawowy bonus obrażeń",
              descriptionOfSkill: "Zwiększenie obrażeń o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 6,
            },
            seventhSkill: {
              nameOfSkill: "Bonus punktów życia",
              descriptionOfSkill: "Zwiększenie punktów życia o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 7,
            },
            eighthSkill: {
              nameOfSkill: "Bonus punktów many",
              descriptionOfSkill: "Zwiększenie punktów many o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 8,
            },
            ninthSkill: {
              nameOfSkill: "Ulepszony bonus mądrości",
              descriptionOfSkill: "Zwiększenie podstawowych punktów inteligencji o 20%",
              valueOfSkill: 0.2,
              numberOfSkill: 9,
            },
            tenthSkill: {
              nameOfSkill: "Ulepszony bonus szcześcia",
              descriptionOfSkill: "Zwiększenie podstawowych punktów szcześcia o 20%",
              valueOfSkill: 0.2,
              numberOfSkill: 10,
            },
            eleventhSkill: {
              nameOfSkill: "Ulepszona regeneracja punktów many",
              descriptionOfSkill: "Zwiększenie regeneracji punktów many w walce o 5 punktów many na sekundę",
              valueOfSkill: 5,
              numberOfSkill: 11,
            },
            twelfthSkill: {
              nameOfSkill: "Mistrzowski bonus obrażeń",
              descriptionOfSkill: "Zwiększenie obrażeń o 25%",
              valueOfSkill: 0.25,
              numberOfSkill: 12,
            },
          };
          break;
        case "Warrior":
          data = {
            firstSkill: {
              nameOfSkill: "Bonus wytrzymałości",
              descriptionOfSkill: "Zwiększenie podstawowych punktów wytrzymałości o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 1,
            },
            secondSkill: {
              nameOfSkill: "Bonus siły",
              descriptionOfSkill: "Zwiększenie podstawowych punktów siły o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 2,
            },
            thirdSkill: {
              nameOfSkill: "Bonus zwinności",
              descriptionOfSkill: "Zwiększenie podstawowych punktów zręczności o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 3,
            },
            forthSkill: {
              nameOfSkill: "Bonus szczęścia",
              descriptionOfSkill: "Zwiększenie podstawowych punktów szczęścia o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 4,
            },
            fifthSkill: {
              nameOfSkill: "Bonus mądrości",
              descriptionOfSkill: "Zwiększenie podstawowych punktów inteligencji o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 5,
            },
            sixthSkill: {
              nameOfSkill: "Podstawowy bonus punktów życia",
              descriptionOfSkill: "Zwiększenie punktów życia o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 6,
            },
            seventhSkill: {
              nameOfSkill: "Bonus do obrony",
              descriptionOfSkill: "Zwiększenie punktów obrony o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 7,
            },
            eighthSkill: {
              nameOfSkill: "Bonus obrażeń",
              descriptionOfSkill: "Zwiększenie obrażeń o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 8,
            },
            ninthSkill: {
              nameOfSkill: "Ulepszony bonus szcześcia",
              descriptionOfSkill: "Zwiększenie podstawowych punktów szcześcia o 20%",
              valueOfSkill: 0.2,
              numberOfSkill: 9,
            },
            tenthSkill: {
              nameOfSkill: "Ulepszony bonus siły",
              descriptionOfSkill: "Zwiększenie podstawowych punktów siły o 20%",
              valueOfSkill: 0.2,
              numberOfSkill: 10,
            },
            eleventhSkill: {
              nameOfSkill: "Ulepszony bonus do obrony",
              descriptionOfSkill: "Zwiększenie punktów obrony o 20%",
              valueOfSkill: 0.2,
              numberOfSkill: 11,
            },
            twelfthSkill: {
              nameOfSkill: "Mistrzowski bonus punktów życia",
              descriptionOfSkill: "Zwiększenie punktów życia o 25%",
              valueOfSkill: 0.25,
              numberOfSkill: 12,
            },
          };
          break;
        case "Hunter":
          data = {
            firstSkill: {
              nameOfSkill: "Bonus zwinności",
              descriptionOfSkill: "Zwiększenie podstawowych punktów zręczności o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 1,
            },
            secondSkill: {
              nameOfSkill: "Bonus wytrzymałości",
              descriptionOfSkill: "Zwiększenie podstawowych punktów wytrzymałości o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 2,
            },
            thirdSkill: {
              nameOfSkill: "Bonus szcześcia",
              descriptionOfSkill: "Zwiększenie podstawowych punktów szcześcia o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 3,
            },
            forthSkill: {
              nameOfSkill: "Bonus siły",
              descriptionOfSkill: "Zwiększenie podstawowych punktów siły o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 4,
            },
            fifthSkill: {
              nameOfSkill: "Bonus mądrości",
              descriptionOfSkill: "Zwiększenie podstawowych punktów inteligencji o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 5,
            },
            sixthSkill: {
              nameOfSkill: "Bonus obrażeń",
              descriptionOfSkill: "Zwiększenie obrażeń o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 6,
            },
            seventhSkill: {
              nameOfSkill: "Bonus punktów życia",
              descriptionOfSkill: "Zwiększenie punktów życia o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 7,
            },
            eighthSkill: {
              nameOfSkill: "Bonus punktów many",
              descriptionOfSkill: "Zwiększenie punktów many o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 8,
            },
            ninthSkill: {
              nameOfSkill: "Ulepszony bonus uniku",
              descriptionOfSkill: "Zwiększenie punktów uniku o 5%",
              valueOfSkill: 5,
              numberOfSkill: 9,
            },
            tenthSkill: {
              nameOfSkill: "Ulepszony bonus szcześcia",
              descriptionOfSkill: "Zwiększenie podstawowych punktów szcześcia o 20%",
              valueOfSkill: 0.2,
              numberOfSkill: 10,
            },
            eleventhSkill: {
              nameOfSkill: "Ulepszony bonus zwinności",
              descriptionOfSkill: "Zwiększenie podstawowych punktów zręczności o 20%",
              valueOfSkill: 0.2,
              numberOfSkill: 11,
            },
            twelfthSkill: {
              nameOfSkill: "Mistrzowski bonus obrażeń",
              descriptionOfSkill: "Zwiększenie obrażeń o 25%",
              valueOfSkill: 0.25,
              numberOfSkill: 12,
            },
          };
          break;
        case "Priest":
          data = {
            firstSkill: {
              nameOfSkill: "Bonus szcześcia",
              descriptionOfSkill: "Zwiększenie podstawowych punktów szcześcia o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 1,
            },
            secondSkill: {
              nameOfSkill: "Bonus mądrości",
              descriptionOfSkill: "Zwiększenie podstawowych punktów inteligencji o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 2,
            },
            thirdSkill: {
              nameOfSkill: "Bonus wytrzymałości",
              descriptionOfSkill: "Zwiększenie podstawowych punktów wytrzymałości o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 3,
            },
            forthSkill: {
              nameOfSkill: "Bonus zwinności",
              descriptionOfSkill: "Zwiększenie podstawowych punktów zręczności o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 4,
            },
            fifthSkill: {
              nameOfSkill: "Bonus siły",
              descriptionOfSkill: "Zwiększenie podstawowych punktów siły o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 5,
            },
            sixthSkill: {
              nameOfSkill: "Bonus punktów życia ",
              descriptionOfSkill: "Zwiększenie punktów życia o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 6,
            },
            seventhSkill: {
              nameOfSkill: "Bonus obrażeń",
              descriptionOfSkill: "Zwiększenie obrażeń  o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 7,
            },
            eighthSkill: {
              nameOfSkill: "Bonus punktów many",
              descriptionOfSkill: "Zwiększenie punktów many o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 8,
            },
            ninthSkill: {
              nameOfSkill: "Ulepszony bonus szcześcia",
              descriptionOfSkill: "Zwiększenie podstawowych punktów szcześcia o 20%",
              valueOfSkill: 0.2,
              numberOfSkill: 9,
            },
            tenthSkill: {
              nameOfSkill: "Ulepszony bonus mądrości",
              descriptionOfSkill: "Zwiększenie podstawowych punktów inteligencji o 20%",
              valueOfSkill: 0.2,
              numberOfSkill: 10,
            },
            eleventhSkill: {
              nameOfSkill: "Ulepszony bonus do regeneracji punktów many",
              descriptionOfSkill: "Zwiększenie regeneracji punktów many w walce o 5 punktów many na sekundę",
              valueOfSkill: 5,
              numberOfSkill: 11,
            },
            twelfthSkill: {
              nameOfSkill: "Mistrzowski bonus punktów many",
              descriptionOfSkill: "Zwiększenie punktów many o 25%",
              valueOfSkill: 0.25,
              numberOfSkill: 12,
            },
          };
          break;
        case "Berserk":
          data = {
            firstSkill: {
              nameOfSkill: "Bonus siły",
              descriptionOfSkill: "Zwiększenie podstawowych punktów siły o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 1,
            },
            secondSkill: {
              nameOfSkill: "Bonus zwinności",
              descriptionOfSkill: "Zwiększenie podstawowych punktów zręczności o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 2,
            },
            thirdSkill: {
              nameOfSkill: "Bonus wytrzymałości",
              descriptionOfSkill: "Zwiększenie podstawowych punktów wytrzymałości o 5%",
              valueOfSkill: 0.05,
              numberOfSkill: 3,
            },
            forthSkill: {
              nameOfSkill: "Bonus szcześcia",
              descriptionOfSkill: "Zwiększenie podstawowych punktów szcześcia o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 4,
            },
            fifthSkill: {
              nameOfSkill: "Bonus mądrości",
              descriptionOfSkill: "Zwiększenie podstawowych punktów inteligencji o 5%",
              valueOfSkill: 0.05,
              numberOfSkill: 5,
            },
            sixthSkill: {
              nameOfSkill: "Bonus siły",
              descriptionOfSkill: "Zwiększenie podstawowych punktów siły o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 6,
            },
            seventhSkill: {
              nameOfSkill: "Bonus obrażeń",
              descriptionOfSkill: "Zwiększenie obrażeń o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 7,
            },
            eighthSkill: {
              nameOfSkill: "Bonus szcześcia",
              descriptionOfSkill: "Zwiększenie podstawowych punktów szcześcia o 10%",
              valueOfSkill: 0.1,
              numberOfSkill: 8,
            },
            ninthSkill: {
              nameOfSkill: "Ulepszony Bonus obrażeń",
              descriptionOfSkill: "Zwiększenie obrażeń o 20%",
              valueOfSkill: 0.2,
              numberOfSkill: 9,
            },
            tenthSkill: {
              nameOfSkill: "Ulepszony Bonus Punktów Życia",
              descriptionOfSkill: "Zwiększenie punktów życia o 20%",
              valueOfSkill: 0.2,
              numberOfSkill: 10,
            },
            eleventhSkill: {
              nameOfSkill: "Ulepszony bonus do regeneracji punktów życia",
              descriptionOfSkill: "Zwiększenie regeneracji punktów życia w walce o 5 punktów życia na sekundę",
              valueOfSkill: 5,
              numberOfSkill: 11,
            },
            twelfthSkill: {
              nameOfSkill: "Mistrzowski bonus obrażeń",
              descriptionOfSkill: "Zwiększenie obrażeń o 25%",
              valueOfSkill: 0.25,
              numberOfSkill: 12,
            },
          };
          break;
      }
      break;
  }
  return data;
}
