 export default function createSkillsToCharacter(heroClass, typeOfSkills) {
    let { data } = {};
    switch (typeOfSkills) {
        case 0:
            switch (heroClass) {
                case 'Mage':
                    data = {
                        firstSkill: {
                            nameOfSkill: "Kula ognia",
                            descriptionOfSpell: "Przywołanie kuli ognia która zadaje duże obrażenia. Zadaje dodatkowe obrażenia od ognia przez określony czas.",
                            pointsOfMana: 25,
                            valueOfSpell: 0.10,
                            durationTime: 0,
                            castTime: 2000,
                            recastTime: 10000,
                            numberOfSkill: 1,
                            countOfDots: 0,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0,
                        },
                        secondSkill: {
                            nameOfSkill: "Błyskawica",
                            descriptionOfSpell: "Zsyła błyskawice na pole walki zadając ogromne obrażenia.",
                            pointsOfMana: 70,
                            valueOfSpell: 0.30,
                            durationTime: 0,
                            castTime: 5000,
                            recastTime: 30000,
                            numberOfSkill: 2,
                            countOfDots: 2,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0.20,
                        },
                        thirdSkill: {
                            nameOfSkill: "Przypływ many",
                            descriptionOfSpell: "Zwiększa poziom many na okres 30 sekund. Ponowne użycie po upłynięciu 2 minut.",
                            pointsOfMana: 70,
                            valueOfSpell: 0.30,
                            durationTime: 30000,
                            castTime: 5000,
                            recastTime: 120000,
                            numberOfSkill: 3,
                            countOfDots: 0,
                            typeOfSkill: 1,
                            targetOfBonusValue:"manaPoints",
                            dotValue:0,
                        },
                        forthSkill: {
                            nameOfSkill: "Medytacja",
                            descriptionOfSpell: "Przywraca określoną ilość punktów many. Możliwe użycie po upłynięciu 30 sekund.",
                            pointsOfMana: 50,
                            valueOfSpell: 0.30,
                            durationTime: 0,
                            castTime: 2000,
                            recastTime: 25000,
                            numberOfSkill: 4,
                            countOfDots: 2,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0,
                        },
                        fifthSkill: {
                            nameOfSkill: "Liściasty bandaż",
                            descriptionOfSpell:"Użycie liściastego bandażu przywraca określoną ilość punktów życia. Możliwe ponowne użycie po upłynięciu 60 sekund.",
                            pointsOfMana: 70,
                            valueOfSpell: 0.30,
                            durationTime: 0,
                            castTime: 5000,
                            recastTime: 30000,
                            numberOfSkill: 5,
                            countOfDots: 0,
                            typeOfSkill: 2,
                            targetOfBonusValue:"regenHp",
                            dotValue:0,
                        },
                        sixthSkill: {
                            nameOfSkill: "Podpalająca strzała",
                            descriptionOfSpell: "Wystrzelenie strzały pokrytej ogniem zadaje obrażenia oraz dodatkowe obrażenia od podpalenia przez dany okres czasu.",
                            pointsOfMana: 50,
                            valueOfSpell: 0.20,
                            durationTime: 0,
                            castTime: 2000,
                            recastTime: 25000,
                            numberOfSkill: 6,
                            countOfDots: 3,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0.10,
                        },
                    };
                    break;
                case 'Warrior':
                    data = {
                        firstSkill: {
                            nameOfSkill: "Złota strzała",
                            descriptionOfSpell: "Powoduje wystrzelenie złotej strzały, która zadaje ogromne obrażenia",
                            pointsOfMana: 25,
                            valueOfSpell: 0.10,
                            durationTime: 0,
                            castTime: 2000,
                            recastTime: 10000,
                            numberOfSkill: 1,
                            countOfDots: 0,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0,
                        },
                        secondSkill: {
                            nameOfSkill: "Zatruta strzała",
                            descriptionOfSpell: "Powoduje wystrzelenie zatrutej strzały, która zadaje dodatkowe obrażenia przez określony czas od zatrucia.",
                            pointsOfMana: 70,
                            valueOfSpell: 0.30,
                            durationTime: 0,
                            castTime: 5000,
                            recastTime: 30000,
                            numberOfSkill: 2,
                            countOfDots: 2,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0.20,
                        },
                        thirdSkill: {
                            nameOfSkill: "Ukrycie w cieniu",
                            descriptionOfSpell: "Zwiększenie szansy na unik o 10% na okres 30 sekund. Ponowne użycie możliwe po upłynieniu 120 sekund.",
                            pointsOfMana: 70,
                            valueOfSpell: 0.30,
                            durationTime: 30000,
                            castTime: 5000,
                            recastTime: 120000,
                            numberOfSkill: 3,
                            countOfDots: 0,
                            typeOfSkill: 1,
                            targetOfBonusValue:"dodge",
                            dotValue:0,
                        },
                        forthSkill: {
                            nameOfSkill: "Czarba strzała",
                            descriptionOfSpell: "Wystrzelenie czarnej grozy, która zadaje ogromne obrażenia poprzez przebicie pancerza. Trudna do zobaczenia.",
                            pointsOfMana: 50,
                            valueOfSpell: 0.30,
                            durationTime: 0,
                            castTime: 2000,
                            recastTime: 25000,
                            numberOfSkill: 4,
                            countOfDots: 2,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0,
                        },
                        fifthSkill: {
                            nameOfSkill: "Liściasty bandaż",
                            descriptionOfSpell:"Użycie liściastego bandażu przywraca określoną ilość punktów życia. Możliwe ponowne użycie po upłynięciu 60 sekund.",
                            pointsOfMana: 70,
                            valueOfSpell: 0.30,
                            durationTime: 0,
                            castTime: 5000,
                            recastTime: 30000,
                            numberOfSkill: 5,
                            countOfDots: 0,
                            typeOfSkill: 2,
                            targetOfBonusValue:"regenHp",
                            dotValue:0,
                        },
                        sixthSkill: {
                            nameOfSkill: "Podpalająca strzała",
                            descriptionOfSpell: "Wystrzelenie strzały pokrytej ogniem zadaje obrażenia oraz dodatkowe obrażenia od podpalenia przez dany okres czasu.",
                            pointsOfMana: 50,
                            valueOfSpell: 0.20,
                            durationTime: 0,
                            castTime: 2000,
                            recastTime: 25000,
                            numberOfSkill: 6,
                            countOfDots: 3,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0.10,
                        },
                    };
                    break;
                case 'Hunter':
                    data = {
                        firstSkill: {
                            nameOfSkill: "Złota strzała",
                            descriptionOfSpell: "Powoduje wystrzelenie złotej strzały, która zadaje ogromne obrażenia",
                            pointsOfMana: 25,
                            valueOfSpell: 0.10,
                            durationTime: 0,
                            castTime: 2000,
                            recastTime: 10000,
                            numberOfSkill: 1,
                            countOfDots: 0,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0,
                        },
                        secondSkill: {
                            nameOfSkill: "Zatruta strzała",
                            descriptionOfSpell: "Powoduje wystrzelenie zatrutej strzały, która zadaje dodatkowe obrażenia przez określony czas od zatrucia.",
                            pointsOfMana: 70,
                            valueOfSpell: 0.30,
                            durationTime: 0,
                            castTime: 5000,
                            recastTime: 30000,
                            numberOfSkill: 2,
                            countOfDots: 2,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0.20,
                        },
                        thirdSkill: {
                            nameOfSkill: "Ukrycie w cieniu",
                            descriptionOfSpell: "Zwiększenie szansy na unik o 10% na okres 30 sekund. Ponowne użycie możliwe po upłynieniu 120 sekund.",
                            pointsOfMana: 70,
                            valueOfSpell: 0.30,
                            durationTime: 30000,
                            castTime: 5000,
                            recastTime: 120000,
                            numberOfSkill: 3,
                            countOfDots: 0,
                            typeOfSkill: 1,
                            targetOfBonusValue:"dodge",
                            dotValue:0,
                        },
                        forthSkill: {
                            nameOfSkill: "Czarba strzała",
                            descriptionOfSpell: "Wystrzelenie czarnej grozy, która zadaje ogromne obrażenia poprzez przebicie pancerza. Trudna do zobaczenia.",
                            pointsOfMana: 50,
                            valueOfSpell: 0.30,
                            durationTime: 0,
                            castTime: 2000,
                            recastTime: 25000,
                            numberOfSkill: 4,
                            countOfDots: 2,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0,
                        },
                        fifthSkill: {
                            nameOfSkill: "Liściasty bandaż",
                            descriptionOfSpell:"Użycie liściastego bandażu przywraca określoną ilość punktów życia. Możliwe ponowne użycie po upłynięciu 60 sekund.",
                            pointsOfMana: 70,
                            valueOfSpell: 0.30,
                            durationTime: 0,
                            castTime: 5000,
                            recastTime: 30000,
                            numberOfSkill: 5,
                            countOfDots: 0,
                            typeOfSkill: 2,
                            targetOfBonusValue:"regenHp",
                            dotValue:0,
                        },
                        sixthSkill: {
                            nameOfSkill: "Podpalająca strzała",
                            descriptionOfSpell: "Wystrzelenie strzały pokrytej ogniem zadaje obrażenia oraz dodatkowe obrażenia od podpalenia przez dany okres czasu.",
                            pointsOfMana: 50,
                            valueOfSpell: 0.20,
                            durationTime: 0,
                            castTime: 2000,
                            recastTime: 25000,
                            numberOfSkill: 6,
                            countOfDots: 3,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0.10,
                        },
                    };
                    break;
                case 'Priest':
                    data = {
                        firstSkill: {
                            nameOfSkill: "Złota strzała",
                            descriptionOfSpell: "Powoduje wystrzelenie złotej strzały, która zadaje ogromne obrażenia",
                            pointsOfMana: 25,
                            valueOfSpell: 0.10,
                            durationTime: 0,
                            castTime: 2000,
                            recastTime: 10000,
                            numberOfSkill: 1,
                            countOfDots: 0,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0,
                        },
                        secondSkill: {
                            nameOfSkill: "Zatruta strzała",
                            descriptionOfSpell: "Powoduje wystrzelenie zatrutej strzały, która zadaje dodatkowe obrażenia przez określony czas od zatrucia.",
                            pointsOfMana: 70,
                            valueOfSpell: 0.30,
                            durationTime: 0,
                            castTime: 5000,
                            recastTime: 30000,
                            numberOfSkill: 2,
                            countOfDots: 2,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0.20,
                        },
                        thirdSkill: {
                            nameOfSkill: "Ukrycie w cieniu",
                            descriptionOfSpell: "Zwiększenie szansy na unik o 10% na okres 30 sekund. Ponowne użycie możliwe po upłynieniu 120 sekund.",
                            pointsOfMana: 70,
                            valueOfSpell: 0.30,
                            durationTime: 30000,
                            castTime: 5000,
                            recastTime: 120000,
                            numberOfSkill: 3,
                            countOfDots: 0,
                            typeOfSkill: 1,
                            targetOfBonusValue:"dodge",
                            dotValue:0,
                        },
                        forthSkill: {
                            nameOfSkill: "Czarba strzała",
                            descriptionOfSpell: "Wystrzelenie czarnej grozy, która zadaje ogromne obrażenia poprzez przebicie pancerza. Trudna do zobaczenia.",
                            pointsOfMana: 50,
                            valueOfSpell: 0.30,
                            durationTime: 0,
                            castTime: 2000,
                            recastTime: 25000,
                            numberOfSkill: 4,
                            countOfDots: 2,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0,
                        },
                        fifthSkill: {
                            nameOfSkill: "Liściasty bandaż",
                            descriptionOfSpell:"Użycie liściastego bandażu przywraca określoną ilość punktów życia. Możliwe ponowne użycie po upłynięciu 60 sekund.",
                            pointsOfMana: 70,
                            valueOfSpell: 0.30,
                            durationTime: 0,
                            castTime: 5000,
                            recastTime: 30000,
                            numberOfSkill: 5,
                            countOfDots: 0,
                            typeOfSkill: 2,
                            targetOfBonusValue:"regenHp",
                            dotValue:0,
                        },
                        sixthSkill: {
                            nameOfSkill: "Podpalająca strzała",
                            descriptionOfSpell: "Wystrzelenie strzały pokrytej ogniem zadaje obrażenia oraz dodatkowe obrażenia od podpalenia przez dany okres czasu.",
                            pointsOfMana: 50,
                            valueOfSpell: 0.20,
                            durationTime: 0,
                            castTime: 2000,
                            recastTime: 25000,
                            numberOfSkill: 6,
                            countOfDots: 3,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0.10,
                        },
                    };
                    break;
                case 'Berserk':
                    data = {
                        firstSkill: {
                            nameOfSkill: "Cios grozy",
                            descriptionOfSpell: "Mocny cios grozy zadaje dodatkowe obrażenia z powodu przerażenia przeciwnika.",
                            pointsOfMana: 25,
                            valueOfSpell: 0.10,
                            durationTime: 0,
                            castTime: 2000,
                            recastTime: 10000,
                            numberOfSkill: 1,
                            countOfDots: 0,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0,
                        },
                        secondSkill: {
                            nameOfSkill: "Podwójne cięcie",
                            descriptionOfSpell: "Wyprowadzenie szybkich dwóch mocnych cięc, które zadają taką samą ilość obrażen",
                            pointsOfMana: 70,
                            valueOfSpell: 0.30,
                            durationTime: 0,
                            castTime: 5000,
                            recastTime: 30000,
                            numberOfSkill: 2,
                            countOfDots: 1,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:1,
                        },
                        thirdSkill: {
                            nameOfSkill: "Wzrok Odyna",
                            descriptionOfSpell: "Zwiększenie szansy na cios krytyczny o 15% na okres 30 sekund. Ponowne użycie po upłynięciu 120 sekund.",
                            pointsOfMana: 70,
                            valueOfSpell: 0.30,
                            durationTime: 30000,
                            castTime: 5000,
                            recastTime: 120000,
                            numberOfSkill: 3,
                            countOfDots: 0,
                            typeOfSkill: 1,
                            targetOfBonusValue:"crit",
                            dotValue:0,
                        },
                        forthSkill: {
                            nameOfSkill: "Zwycięski róg",
                            descriptionOfSpell: "Przywraca określoną ilość punktów życia. Ponowne wykorzystanie umiejętności po upłynięciu 120 sekund.",
                            pointsOfMana: 50,
                            valueOfSpell: 0.30,
                            durationTime: 0,
                            castTime: 2000,
                            recastTime: 25000,
                            numberOfSkill: 4,
                            countOfDots: 2,
                            typeOfSkill: 2,
                            targetOfBonusValue:"regenHp",
                            dotValue:0,
                        },
                        fifthSkill: {
                            nameOfSkill: "Krwawe cięcie",
                            descriptionOfSpell:"Wyprowadzenie groźnego ataku przebijający pancerz zostawiający głeboką ranę. Dodatkowe obrażenia od krwawienia przez określony czas.",
                            pointsOfMana: 70,
                            valueOfSpell: 0.30,
                            durationTime: 0,
                            castTime: 5000,
                            recastTime: 30000,
                            numberOfSkill: 5,
                            countOfDots: 3,
                            typeOfSkill: 0,
                            targetOfBonusValue:"attack",
                            dotValue:0.30,
                        },
                        sixthSkill: {
                            nameOfSkill: "Wściekłóść wikinga",
                            descriptionOfSpell: "Wszystkie wyprowadzone obrażenia są zwiększone o 25% na okres 30 sekund. Ponowne użycie po upłynięciu 120 sekund.",
                            pointsOfMana: 50,
                            valueOfSpell: 0.20,
                            durationTime: 0,
                            castTime: 2000,
                            recastTime: 25000,
                            numberOfSkill: 6,
                            countOfDots: 3,
                            typeOfSkill: 1,
                            targetOfBonusValue:"damage",
                            dotValue:0.10,
                        },
                    };
                    break;
            };
            break;
         case 1:
            switch (heroClass) {
                case 'Mage':
                    data = {
                        firstSkill: {
                            nameOfSkill: "Bonus inteligencji",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów inteligencji o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:1,
                        },
                        secondSkill: {
                            nameOfSkill: "Bonus wytrzymałości",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów wytrzymałości o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:2,
                            
                        },
                        thirdSkill: {
                            nameOfSkill: "Bonus szczęścia",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów szczęścia o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:3,
                        },
                        forthSkill: {
                            nameOfSkill: "Bonus zwinności",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów zręczności o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:4,
                        },
                        fifthSkill: {
                            nameOfSkill: "Bonus siły",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów siły o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:5,
                        },
                        sixthSkill: {
                            nameOfSkill: "Podstawowy bonus obrażeń",
                            descriptionOfSpell: "Zwiększenie obrażeń o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:6,
                        },
                        seventhSkill: {
                            nameOfSkill: "Bonus punktów życia",
                            descriptionOfSpell: "Zwiększenie punktów życia o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:7,
                        },
                        eighthSkill: {
                            nameOfSkill: "Bonus punktów many",
                            descriptionOfSpell: "Zwiększenie punktów many o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:8,
                        },
                        ninthSkill: {
                            nameOfSkill: "Ulepszony bonus mądrości",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów inteligencji o 20%",
                            valueOfBonus: 0.20,
                            numberOfSkill:9,
                        },
                        tenthSkill: {
                            nameOfSkill: "Ulepszony bonus szcześcia",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów szcześcia o 20%",
                            valueOfBonus: 20,
                            numberOfSkill:10,
                        },
                        eleventhSkill: {
                            nameOfSkill: "Ulepszona regeneracja punktów many",
                            descriptionOfSpell: "Zwiększenie regeneracji punktów many w walce o 5 punktów many na sekundę",
                            valueOfBonus: 5,
                            numberOfSkill:11,
                        },
                        twelfthSkill: {
                            nameOfSkill: "Mistrzowski bonus obrażeń",
                            descriptionOfSpell: "Zwiększenie obrażeń o 25%",
                            valueOfBonus: 0.25,
                            numberOfSkill:12,
                        },
                    };
                    break;
                case 'Warrior':
                    data = {
                        firstSkill: {
                            nameOfSkill: "Bonus wytrzymałości",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów wytrzymałości o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:1,
                        },
                        secondSkill: {
                            nameOfSkill: "Bonus siły",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów siły o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:2,
                        },
                        thirdSkill: {
                            nameOfSkill: "Bonus zwinności",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów zręczności o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:3,
                        },
                        forthSkill: {
                            nameOfSkill: "Bonus szczęścia",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów szczęścia o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:4,
                        },
                        fifthSkill: {
                            nameOfSkill: "Bonus mądrości",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów inteligencji o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:5,
                        },
                        sixthSkill: {
                            nameOfSkill: "Podstawowy bonus punktów życia",
                            descriptionOfSpell: "Zwiększenie punktów życia o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:6,
                        },
                        seventhSkill: {
                            nameOfSkill: "Bonus do obrony",
                            descriptionOfSpell: "Zwiększenie punktów obrony o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:7,
                        },
                        eighthSkill: {
                            nameOfSkill: "Bonus obrażeń",
                            descriptionOfSpell: "Zwiększenie obrażeń o 10%",
                            valueOfBonus: 10,
                            numberOfSkill:8,
                        },
                        ninthSkill: {
                            nameOfSkill: "Ulepszony bonus szcześcia",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów szcześcia o 20%",
                            valueOfBonus: 0.20,
                            numberOfSkill:9,
                        },
                        tenthSkill: {
                            nameOfSkill: "Ulepszony bonus siły",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów siły o 20%",
                            valueOfBonus: 0.20,
                            numberOfSkill:10,
                        },
                        eleventhSkill: {
                            nameOfSkill: "Ulepszony bonus do obrony",
                            descriptionOfSpell: "Zwiększenie punktów obrony o 20%",
                            valueOfBonus: 0.20,
                            numberOfSkill:11,
                        },
                        twelfthSkill: {
                            nameOfSkill: "Mistrzowski bonus punktów życia",
                            descriptionOfSpell: "Zwiększenie punktów życia o 25%",
                            valueOfBonus: 0.25,
                            numberOfSkill:12,
                        },
                    };                   
                    break;
                case 'Hunter':
                    data = {
                        firstSkill: {
                            nameOfSkill: "Bonus zwinności",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów zręczności o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:1,
                        },
                        secondSkill: {
                            nameOfSkill: "Bonus wytrzymałości",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów wytrzymałości o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:2,
                        },
                        thirdSkill: {
                            nameOfSkill: "Bonus szcześcia",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów szcześcia o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:3,
                        },
                        forthSkill: {
                            nameOfSkill: "Bonus siły",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów siły o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:4,
                        },
                        fifthSkill: {
                            nameOfSkill: "Bonus mądrości",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów inteligencji o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:5,
                        },
                        sixthSkill: {
                            nameOfSkill: "Bonus obrażeń",
                            descriptionOfSpell: "Zwiększenie obrażeń o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:6,
                        },
                        seventhSkill: {
                            nameOfSkill: "Bonus punktów życia",
                            descriptionOfSpell: "Zwiększenie punktów życia o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:7,
                        },
                        eighthSkill: {
                            nameOfSkill: "Bonus punktów many",
                            descriptionOfSpell: "Zwiększenie punktów many o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:8,
                        },
                        ninthSkill: {
                            nameOfSkill: "Ulepszony bonus uniku",
                            descriptionOfSpell: "Zwiększenie punktów uniku o 5%",
                            valueOfBonus: 5,
                            numberOfSkill:9,
                        },
                        tenthSkill: {
                            nameOfSkill: "Ulepszony bonus szcześcia",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów szcześcia o 20%",
                            valueOfBonus: 0.20,
                            numberOfSkill:10,
                        },
                        eleventhSkill: {
                            nameOfSkill: "Ulepszony bonus zwinności",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów zręczności o 20%",
                            valueOfBonus: 0.20,
                            numberOfSkill:11,
                        },
                        twelfthSkill: {
                            nameOfSkill: "Mistrzowski bonus obrażeń",
                            descriptionOfSpell: "Zwiększenie obrażeń o 25%",
                            valueOfBonus: 0.25,
                            numberOfSkill:12,
                        },
                    };                   
                    break;
                case 'Priest':
                    data = {
                        firstSkill: {
                            nameOfSkill: "Bonus szcześcia",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów szcześcia o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:1,
                        },
                        secondSkill: {
                            nameOfSkill: "Bonus mądrości",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów inteligencji o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:2,
                        },
                        thirdSkill: {
                            nameOfSkill: "Bonus wytrzymałości",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów wytrzymałości o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:3,
                        },
                        forthSkill: {
                            nameOfSkill: "Bonus zwinności",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów zręczności o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:4,
                        },
                        fifthSkill: {
                            nameOfSkill: "Bonus siły",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów siły o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:5,
                        },
                        sixthSkill: {
                            nameOfSkill: "Bonus punktów życia ",
                            descriptionOfSpell: "Zwiększenie punktów życia o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:6,
                        },
                        seventhSkill: {
                            nameOfSkill: "Bonus obrażeń",
                            descriptionOfSpell: "Zwiększenie obrażeń  o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:7,
                        },
                        eighthSkill: {
                            nameOfSkill: "Bonus punktów many",
                            descriptionOfSpell: "Zwiększenie punktów many o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:8,
                        },
                        ninthSkill: {
                            nameOfSkill: "Ulepszony bonus szcześcia",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów szcześcia o 20%",
                            valueOfBonus: 0.20,
                            numberOfSkill:9,
                        },
                        tenthSkill: {
                            nameOfSkill: "Ulepszony bonus mądrości",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów inteligencji o 20%",
                            valueOfBonus: 0.20,
                            numberOfSkill:10,
                        },
                        eleventhSkill: {
                            nameOfSkill: "Ulepszony bonus do regeneracji punktów many",
                            descriptionOfSpell: "Zwiększenie regeneracji punktów many w walce o 5 punktów many na sekundę",
                            valueOfBonus: 5,
                            numberOfSkill:11,
                        },
                        twelfthSkill: {
                            nameOfSkill: "Mistrzowski bonus punktów many",
                            descriptionOfSpell: "Zwiększenie punktów many o 25%",
                            valueOfBonus: 0.25,
                            numberOfSkill:12,
                        },
                    };                
                    break;
                case 'Berserk':
                    data = {
                        firstSkill: {
                            nameOfSkill: "Bonus siły",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów siły o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:1,
                        },
                        secondSkill: {
                            nameOfSkill: "Bonus zwinności",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów zręczności o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:2,
                        },
                        thirdSkill: {
                            nameOfSkill: "Bonus wytrzymałości",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów wytrzymałości o 5%",
                            valueOfBonus: 0.05,
                            numberOfSkill:3,
                        },
                        forthSkill: {
                            nameOfSkill: "Bonus szcześcia",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów szcześcia o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:4,
                        },
                        fifthSkill: {
                            nameOfSkill: "Bonus mądrości",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów inteligencji o 5%",
                            valueOfBonus: 0.05,
                            numberOfSkill:5,
                        },
                        sixthSkill: {
                            nameOfSkill: "Bonus siły",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów siły o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:6,
                        },
                        seventhSkill: {
                            nameOfSkill: "Bonus obrażeń",
                            descriptionOfSpell: "Zwiększenie obrażeń o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:7,
                        },
                        eighthSkill: {
                            nameOfSkill: "Bonus szcześcia",
                            descriptionOfSpell: "Zwiększenie podstawowych punktów szcześcia o 10%",
                            valueOfBonus: 0.10,
                            numberOfSkill:8,
                        },
                        ninthSkill: {
                            nameOfSkill: "Ulepszony Bonus obrażeń",
                            descriptionOfSpell: "Zwiększenie obrażeń o 20%",
                            valueOfBonus: 0.20,
                            numberOfSkill:9,
                        },
                        tenthSkill: {
                            nameOfSkill: "Ulepszony Bonus Punktów Życia",
                            descriptionOfSpell: "Zwiększenie punktów życia o 20%",
                            valueOfBonus: 0.20,
                            numberOfSkill:10,
                        },
                        eleventhSkill: {
                            nameOfSkill: "Ulepszony bonus do regeneracji punktów życia",
                            descriptionOfSpell: "Zwiększenie regeneracji punktów życia w walce o 5 punktów życia na sekundę",
                            valueOfBonus: 5,
                            numberOfSkill:11,
                        },
                        twelfthSkill: {
                            nameOfSkill: "Mistrzowski bonus obrażeń",
                            descriptionOfSpell: "Zwiększenie obrażeń o 25%",
                            valueOfBonus: 0.25,
                            numberOfSkill:12,
                        },
                    };                    
                    break;
            };
        break;
    };
    return data;
}